= Development Environment

Blended is build with Apache Maven and the polyglot-scala Extension.
Some project need additional tools, but we try to orchestrate those tools by Maven.

Unfortunatelly, most IDEs don't support polyglot-scala yet, so it is required to generate and update `pom.xml` files from the `pom.scala` buildfiles.

== Requirements

To use Maven with the polyglot-scala extension, you need at least Maven 3.3.1.

== Maven issues

=== Parent poms

Large Maven multi-projects setups have issues with parent poms, when they are also part of the project.
The way a parent pom is choosen (either the local version or the installed version from the local repository) is more or less indeterministic, to say the least.

Historically, we tried to work around it by haven a dedicated "parent" profile.

With polyglot-scala extension and it's support for include files, we try to abandon parent poms completely.


== Generating `pom.xml` files

 To generate `pom.xml` from the `pom.scala` files, you can use the `blended-build/gen-pom-xml.sh` script, which works recursively.

 Please note, that you can use the `blended-build/del-pom-xml.sh` script to remove these poms.

== Working with IntelliJ IDEA

After generating the `pom.xml` files, you can import the Maven project as usual.

== Working with Eclipse IDE

Eclipse needs the `pom.xml` files, so you first must ensure to generate the `pom.xml` files.

After that, you can use the script `blended-build/make-m2e-projects.sh` to generate or update the Eclipse project files, which can than be imported into Eclipse as usual.
