= Docker notes

In *blended* we use for integration testing. In our build process we declare some test containers and subsequently those are packaged as docker images in preparation for the integration tests.

== Docker version

We use https://www.docker.com/technologies/overview[docker] version 1.12.3.

== Docker Maven support

Within Maven we use a https://github.com/alexec/docker-maven-plugin[docker maven plugin].

== Using Maven with docker

Since version 1.12 docker does not allow non-secure connections to it's rest API. Usually with docker the required certificates are also installed on the machine and an environment variable `DOCKER_CERT_PATH` is set. This variable points to the directory which contains the certificates to connect to the docker daemon.

To use the certifactes with Java we have to create a keystore containing dockker's root certificate or docker's root certificate to an existing keystore.

....
$ keytool -importcert -file $DOCKER_CERT_PATH/cert.pem -keystore /tmp/mystore
Enter keystore password:
Re-enter new password:
Owner: O=andreas
Issuer: O=andreas
Serial number: 4a37f9e449ec328872e41b2b8352e4ea
Valid from: Sun Oct 04 15:24:00 CEST 2015 until: Tue Sep 18 15:24:00 CEST 2018
Certificate fingerprints:
	 MD5:  31:8C:B8:DF:22:38:87:4A:34:44:1B:42:24:0F:DA:B9
	 SHA1: 5B:C8:27:FC:15:0E:98:C9:0E:98:03:00:94:0D:ED:26:2E:F5:17:9C
	 SHA256: 5B:0B:9D:58:53:BB:94:50:9C:51:A9:58:32:87:C5:47:68:EB:B3:34:66:B0:0E:CC:3D:F1:F1:80:A2:BE:84:54
	 Signature algorithm name: SHA256withRSA
	 Version: 3

Extensions:

#1: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:false
  PathLen: undefined
]

#2: ObjectId: 2.5.29.37 Criticality=false
ExtendedKeyUsages [
  clientAuth
]

#3: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  DigitalSignature
]

Trust this certificate? [no]:  yes
Certificate was added to keystore
....

In order to use the imported certificates with maven, you have to use the created keystore as the keystore for ssl connections by including the following system properties in the maven build:

....
-Djavax.net.ssl.trustStore=/tmp/mystore -Djavax.net.ssl.trustStorePassword=!YOURPASSWORD!
....

.Note for OS X users
****
On OS X the docker daemon does not run directly on the operating system, but within a small virtual box container. As a result, the docker daemon host is not `localhost` on OS X, but the IP address of the virtual box container. It is a good idea to use the virtual box configuration tools to make that IP address static, so that it does not change over time.
****

== Using the demo containers manually

Currently blended contains two demo containers: One container is acting as a management server and the other container is a sample container with some integration routes and REST services. Within blended all _node_-container try to connect to the management server in order to report their status and also aquire configuration or bundle updates.

The demo containers and their corresponding docker images are configured so that they can connect to each other.

Once both containers are started after a few seconds the node container will have reported itself to the management node.

=== Starting the management container

To start the management container we simply start the docker image with a given name. The given name makes it easier to link the node container to the management container later on.

....
docker run -itP --name mgmt atooni/blended_mgmt
....


=== Starting and connecting the node container

When we start the node container we have to link it to the management container. The link comes in 2 parts. The first part is the _docker name_. In our case the name is _mgmt_. In case you have chosen not to select the name yourself, ou have to query docker to find out what the name is.

The second part is the name the node container can use as a DNS name to contact the management server. It is important, that this second part is _mgmt_ or the node will not find it's management connection.

....
docker run -itP --name node --link mgmt:mgmt atooni/blended_node
....