= Blended Launcher Overview

== Components

* Blended Launcher - a classic OSGi framework launcher, able to load and start bundles, and supports Blended specifics

* JvmLauncher - a launcher to start a wrapper JVM, which itself starts the Blended Launcher. This launcher can control JVM settings and restarts of the inner JVM.

== JvmLauncher

=== Commandline Options

----
jvmlauncher start|stop
            -cp=<CLASSPATH>
            [-jvmOpt=<JVMOPTS>]
            [-restartDelay=<DELAY>]
            [-- <INNERJVMOPTS>]
----


== OLD CONTENT

FeatureConfig::
Configuration of plugin- and feature-IDs needed to provide a specific feature.

RuntimeConfig::
Configuration of various settings and plugin- and feature-IDs needed to provide a runnable OSGi container.

ResolvedRuntimeConfig::
A RuntimeConfig, in which are all references to feature-IDs are also embedded in their resolved form (FeatureConfig).

OverlayConfig::
Configuration of additional configuration generators.

LocalRuntimeConfig::
A materialized and resolved RuntimeConfig with optional applied Overlays.
