= Blended REST API

== mgmt: Management API via `blended.mgmt.rest`

Case classes are converted to JSON with prickle.

GET `mgmt/container`::
Description: List all known remote container states. +
Response: `Seq[RemoteContainerState]`

POST `mgmt/container`::
Description: Add new or update container info. +
Parameter: `ContainerInfo`

GET `mgmt/overlayConfig`::
Description: List all registered overlay configs. +
Response: `Seq[OverlayConfig]`

POST `mgmt/overlayConfig`::
Description: Registers a new overlay config. +
Parameter: `OverlayConfig`

GET `mgmt/runtimeConfig`::
Description: List all registered overlay configs. +
Response: `Seq[RuntimeConfig]`

POST `mgmt/runtimeConfig`::
Description: Registers a new runtime config. +
Parameter: `RuntimeConfig`

POST `mgmt/container/{containerId}/update`::
Description: Record an update action for the given containerId. +
Parameter: `UpdateAction`

POST `mgmt/rollout/profile`::
Description: Record a given collection of containers for a new profile rollout. +
Parameter: `RolloutProfile`

== mgmt.repo: Repository Access via `blended.mgmt.repo.rest`

GET `artifacts/{repoId}/{groupId}/{artifactId}/{version}/{artifactId}-{version}[-{classifier}].{type}`::
Description: Download a specific artifact with given from the repository with ID `repoId` and the given coordinates (`groupId`, `artifactId`, `version`, `type` and the optional `classifier`). +
Response: Artifact as download
