:jbake-type: page
:jbake-status: published
== Build file structure

_Blended_ uses `sbt 1.2.6` to build. Currently we have a bit more than 60 submodules in _Blended_, so that the build
file structure needs a bit of explanation:

* The main build file ist `build.sbt` in the root directory of the checkout. The build file is augmented with `.scala` files in the `project`-directory.

* The `project`-directory contains *exactly 1* scala file per sub module. These file can be seen as factories for sbt project references, so that each submodule scala file creates the project reference for that particular submodule.

* All submodule specific settings live in the corresponding scala file, *no exceptions (NONE !)*.

* A sample scala file would be `BlendedActivemqClient.scala`:

[source,scala,linenums]
----
include::../../project/BlendedActivemqClient.scala[]
----

* All sub module files mix in the trait `ProjectFactory`, which means they have to expose a `val` of type `Project`.

* Internally we are using a SettingsFactory `ProjectSettings`. This factory is a class which encapsulates the settings for our submodules based on a handful of configuration parameters which are passed to the factory as constructor arguments.

* The factory exposes a variable `baseProject' which needs to be enriched with the dependencies to other submodules within the project. These dependencies are simply the exposed projects of other sub modules.

* As most of our sub modules are OSGi bundles, the constructor argument `adaptBundle` allows to modify the default bundle settings encapsulated in `BlendedBundle` simply by using the copy method. The resulting OSGi settings will be part of the generated sub module settings.

To complete the example, here is how the sub module above is referenced in the `build.sbt`:

[source,scala]
----
include::../../build.sbt[tags=Building]
----

=== Special cases

There are more complex project definitions, e.g. when the submodule needs to generate an extra artifact in the form of a zip file. An example for such a setup can be seen in https://github.com/woq-blended/blended/blob/master/project/BlendedLauncher.scala[`BlendedLauncher`].

== Set up for Automated releases via travis

TODO

[graphviz, sample, svg]
----
digraph G {Hello->World}
----

[mermaid, test, svg]
----
sequenceDiagram
    participant Alice
    participant Bob
    Alice->John: Hello John, how are you?
    loop Healthcheck
        John->John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail...
    John-->Alice: Great!
    John->Bob: How about you?
    Bob-->John: Jolly good!
----

[plantuml, uml, svg]
----
@startuml
Alice -> Bob: Authentication Request

alt successful case

	Bob -> Alice: Authentication Accepted

else some kind of failure

	Bob -> Alice: Authentication Failure
	group My own label
		Alice -> Log : Log attack start
	    loop 1000 times
	        Alice -> Bob: DNS Attack
	    end
		Alice -> Log : Log attack end
	end

else Another type of failure

   Bob -> Alice: Please repeat

end
@enduml
----



