package blended.launcher

import java.io.File

import blended.launcher.test_generated.TestOsgiFrameworks
import blended.testsupport.TestFile
import blended.testsupport.scalatest.LoggingFreeSpec

class OsgiFrameworksTest extends LoggingFreeSpec
  with TestFile {

  implicit val deletePolicy = TestFile.DeleteWhenNoFailure

  /**
   * This test tests the [[Launcher]] with various OSGi Frameworks.
   * The used [[TestOsgiFrameworks]] class is generated by mill, which is also
   * responsible for providing the framework JAR.
   */
  "Minimal launcher with just the framework JAR" - {

    TestOsgiFrameworks.frameworks.foreach { case (frameworkName, frameworkJar) =>
      frameworkName in {
        assert(new File(frameworkJar).exists() == true, s"Framework JAR file does not exists: ${frameworkJar}")
        val launcherConfig =
          s"""frameworkBundle = "${frameworkJar}"
             |startLevel = 10
             |defaultStartLevel = 4
             |frameworkProperties = {
             |  org.osgi.framework.storage.clean = onFirstInit
             |}
             |bundles = []
             |""".stripMargin

        withTestFile(launcherConfig) { configFile =>
          Launcher.run(Array(
            "--config", configFile.getAbsolutePath(),
            "--test"
          ))
        }
      }
    }
  }
}

