= Blended Updater

== Internal / Development

=== Materializing an update

** download all artifacts referenced in that config
** check checksums of all artifacts
** generate a `LauncherConfig` from the config
** restart the container

=== Config types

The `LauncherConfig` contains only locally available jars and is used to bootstrap the OSGi container. It is processed by the `blender-launcher` module.

The `RuntimeConfig` is the notion of an updateable configuration. It contains some metadata and all artifact locations as URLs.  It is processed by the `blended-updater` module.

After a successful download and integrity check of all artifacts references in a `RuntimeConfig`, a `LauncherConfig` will be generated. All relevant metadata required to map a generated `LauncherConfig` to its producing `RuntimeConfig` will be stored in the `branding` property of the `LauncherConfig`.

New: If all required artifacts are present, the launcher is also able to start directly with a `RuntimeConfig`.

=== TODOs

* Also download configuration files
* Rework profile layout:
** currently, all downloaded JARs lie in the profile directory `profiles/<name>/<version>`.
** goal: downloaded JARs should be kept in a sub directory, next to a new `etc` directory

* Redownload of JARs with incorrect checksums (retry-count)

* Move download configuration to config file
