on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        java-version: [1.8, 11]
        scala-version: [2.12.11, 2.13.2]

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - name: Blended version
      run: ./millw -i show blendedVersion

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Run tests
      run: ./millw -i -j 0 -k blended[${{ matrix.scala-version }}].__.testCached

    - name: Upload test logs
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-logs
        path: out/testlog-*/

    - name: Generate coverage report
      run: ./millw -i scoverage.xmlReportAll

    - name: Upload coverage
      run: bash scripts/codecov_upload.sh -f out/scoverage/xmlReportAll/dest/scoverage.xml -v